### ISSUE TITLE
Registration submit button not working

### ISSUE THREAD

**Issue by neskov7** [marioguerriero/opengram#11]
Registration form submit button is not working although "fix register API request" commit.
This is what npm and chrome console show
![image](https://cloud.githubusercontent.com/assets/18363200/20304134/fc90f72c-ab2e-11e6-97d7-0be07a06dc74.png)

**UPDATE**

API return 409 Conflict message after the registration button is pressed.

**Comment by marioguerriero** [comment]
Testing on the deployed instance ([https://opengram.herokuapp.com/](https://opengram.herokuapp.com/)) this bug seems to be fixed. Anyway the API returns a 409 Conflict message after the registration button is preseed.

**Comment by marioguerriero** [comment]
I'm marking this issue as invalid because I'm unable to reproduced it in any way.
